[package]
name = "flappy"
version = "0.1.0"
authors = ["Bruno Ricci <brricci@orange.fr>"]
edition = "2021"

[[bin]]
name =  "game1"
path = "src/main.rs"

[[bin]]
name = "dungeon"
path = "src/game2.rs"

[dependencies]
bracket-lib = "0.8.7"